========================================================
-> Copy src directory files to the build directory... OK
========================================================
===============================================
-> Run prepare script in the build directory...
===============================================

-> Binary and version used:
-> /home/yanis/Baltiks/Algo_QC_1.9.2/Algo_QC_1.9.2_opt
-> 1.9.2
================================================
-> Running commands in the ./build/cmds file ...
================================================

-> Running the calculation of the test_diffusion data file in the VX_DIRX directory ...
-> Calculation test_diffusion produced an error !
-> Look at the /home/yanis/Baltiks/Algo_QC_1.9.2/share/Validation/Rapports_automatiques/test_diffusion_smagorinsky_anisotrope/build/VX_DIRX/test_diffusion.err file.
grep: test_diffusion.TU: No such file or directory
grep: test_diffusion.TU: No such file or directory
-> Running the post_run script in the VX_DIRX directory ...
Running: cli3.3.2 -nowin -s instructions_ana_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_x.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_x.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_y.pyRunning: cli3.3.2 -nowin -s instructions_simu_dv_y.py

Running: cli3.3.2 -nowin -s instructions_error_dv_y.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_z.py
Running: cli3.3.2 -nowin -s instructions_error_dv_z.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_z.py

-> Running the calculation of the test_diffusion data file in the VY_DIRX directory ...
-> Calculation test_diffusion produced an error !
-> Look at the /home/yanis/Baltiks/Algo_QC_1.9.2/share/Validation/Rapports_automatiques/test_diffusion_smagorinsky_anisotrope/build/VY_DIRX/test_diffusion.err file.
grep: test_diffusion.TU: No such file or directory
grep: test_diffusion.TU: No such file or directory
-> Running the post_run script in the VY_DIRX directory ...
Running: cli3.3.2 -nowin -s instructions_ana_dv_x.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_y.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_y.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_y.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_z.pyRunning: cli3.3.2 -nowin -s instructions_simu_dv_z.py

Running: cli3.3.2 -nowin -s instructions_error_dv_z.py

-> Running the calculation of the test_diffusion data file in the VZ_DIRX directory ...
-> Calculation test_diffusion produced an error !
-> Look at the /home/yanis/Baltiks/Algo_QC_1.9.2/share/Validation/Rapports_automatiques/test_diffusion_smagorinsky_anisotrope/build/VZ_DIRX/test_diffusion.err file.
grep: test_diffusion.TU: No such file or directory
grep: test_diffusion.TU: No such file or directory
-> Running the post_run script in the VZ_DIRX directory ...
Running: cli3.3.2 -nowin -s instructions_simu_dv_x.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_y.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_y.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_y.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_z.py
Running: cli3.3.2 -nowin -s instructions_error_dv_z.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_z.py
Running: cli3.3.2 -nowin -s instructions_error_dv_x.py

-> Running the calculation of the test_diffusion data file in the VX_DIRY directory ...
-> Calculation test_diffusion produced an error !
-> Look at the /home/yanis/Baltiks/Algo_QC_1.9.2/share/Validation/Rapports_automatiques/test_diffusion_smagorinsky_anisotrope/build/VX_DIRY/test_diffusion.err file.
grep: test_diffusion.TU: No such file or directory
grep: test_diffusion.TU: No such file or directory
-> Running the post_run script in the VX_DIRY directory ...
Running: cli3.3.2 -nowin -s instructions_simu_dv_x.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_y.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_y.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_y.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_z.py
Running: cli3.3.2 -nowin -s instructions_error_dv_z.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_z.py

-> Running the calculation of the test_diffusion data file in the VY_DIRY directory ...
-> Calculation test_diffusion produced an error !
-> Look at the /home/yanis/Baltiks/Algo_QC_1.9.2/share/Validation/Rapports_automatiques/test_diffusion_smagorinsky_anisotrope/build/VY_DIRY/test_diffusion.err file.
grep: test_diffusion.TU: No such file or directory
grep: test_diffusion.TU: No such file or directory
-> Running the post_run script in the VY_DIRY directory ...
Running: cli3.3.2 -nowin -s instructions_ana_dv_x.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_y.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_y.py
Running: cli3.3.2 -nowin -s instructions_error_dv_z.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_z.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_z.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_y.py

-> Running the calculation of the test_diffusion data file in the VZ_DIRY directory ...
-> Calculation test_diffusion produced an error !
-> Look at the /home/yanis/Baltiks/Algo_QC_1.9.2/share/Validation/Rapports_automatiques/test_diffusion_smagorinsky_anisotrope/build/VZ_DIRY/test_diffusion.err file.
grep: test_diffusion.TU: No such file or directory
grep: test_diffusion.TU: No such file or directory
-> Running the post_run script in the VZ_DIRY directory ...
Running: cli3.3.2 -nowin -s instructions_simu_dv_x.py
Running: cli3.3.2 -nowin -s instructions_error_dv_x.pyRunning: cli3.3.2 -nowin -s instructions_ana_dv_x.py

Running: cli3.3.2 -nowin -s instructions_ana_dv_y.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_y.py
Running: cli3.3.2 -nowin -s instructions_ana_dv_z.py
Running: cli3.3.2 -nowin -s instructions_error_dv_y.py
Running: cli3.3.2 -nowin -s instructions_error_dv_z.py
Running: cli3.3.2 -nowin -s instructions_simu_dv_z.py
==============================
-> Building PDF report file...
==============================
Traceback (most recent call last):
  File "/home/yanis/triou/TRUST/Validation/Outils/Genere_courbe/src/genererCourbes.py", line 676, in <module>
    app.genererRapport(debug_figure)
  File "/home/yanis/triou/TRUST/Validation/Outils/Genere_courbe/src/genererCourbes.py", line 480, in genererRapport
    indice = chapitre.genererGraphes(destTMP, indice,debug_figure, self.novisit)
  File "/home/yanis/triou/TRUST/Validation/Outils/Genere_courbe/src/GenericSection.py", line 65, in genererGraphes
    figure.genererGraphe(dest, indice,debug_figure)
  File "/home/yanis/triou/TRUST/Validation/Outils/Genere_courbe/src/Visu.py", line 263, in genererGraphe
    field, loc, dom = FileAccumulator.ParseDirectName(plot[2])
  File "/home/yanis/triou/TRUST/Validation/Outils/Genere_courbe/src/filelist.py", line 123, in ParseDirectName
    raise ValueError("Invalid field name: %s" % name)
ValueError: Invalid field name: simu_dv_x
